

USE MODELOXBOX

SELECT * FROM MODELOXBOX.DBO.PRODUTO
SELECT * FROM MODELOXBOX.DBO.PRODUTOGENERO
SELECT * FROM MODELOXBOX.DBO.PRODUTOTIPO
SELECT * FROM MODELOXBOX.DBO.ENDERECO


SELECT * FROM MODELOXBOX.DBO.OrderItems
SELECT * FROM MODELOXBOX.DBO.Products
SELECT * FROM MODELOXBOX.DBO.[Order]
SELECT * FROM MODELOXBOX.DBO.ProductBrands
SELECT * FROM MODELOXBOX.DBO.ProductTypes
SELECT * FROM MODELOXBOX.DBO.DeliveryMethods


ALTER TABLE MODELOXBOX.DBO.PRODUTO ALTER COLUMN Descrição VARCHAR(1000)


